### ISSUE TITLE
Absent loadBalancerSourceRanges in helm chart

### ISSUE THREAD

**Issue by KosShutenko** [percona/percona-postgresql-operator#602]
Hello,

I've found issue with loadBalancerSourceRanges. Its absent in Helm chart for values.proxy.pgBouncer.expose section.

Due to CDR spec on https://github.com/percona/percona-postgresql-operator/blob/main/deploy/cr.yaml we can see that loadBalancerSourceRanges persist on line 72. However in Helm chart this parameter absent. You can see it in template file https://github.com/percona/percona-helm-charts/blob/main/charts/pg-db/templates/cluster.yaml (look at line 181 and below)

Please add this parameter in Helm chart.

Thank you.

**Comment by spron-in** [comment]
Hello @KosShutenko ,

the thing that Operator does not properly support it yet. It was solved in https://github.com/percona/percona-postgresql-operator/pull/532 (or https://jira.percona.com/browse/K8SPG-389).

And will be propagated to helm chart after the release 2.3.0 this month.

**Comment by spron-in** [comment]
This was fixed and now supported in the helm chart. https://github.com/percona/percona-helm-charts/blob/main/charts/pg-db/templates/cluster.yaml#L195

Please try it out.
