### ISSUE TITLE
Failed to create PostgreSQL deployment due to resource requests and limits were missing in the sts

### ISSUE THREAD

**Issue by ChristianHeich-bosch** [percona/percona-postgresql-operator#675]
### Report

Hi Percona team,

I wanted to deploy a PostgreSQL service instance via your operator in my Rancher cluster. I used the example yaml config (https://github.com/percona/percona-postgresql-operator/blob/main/deploy/cr.yaml) and added the resource requests and limit parameter as described in the custom resource options (https://docs.percona.com/percona-operator-for-postgresql/2.0/operator.html) and deployed it via kubectl but the statefullsets didn't use the specified resources. The resources of the statefullsets were empty.

Thanks and regards,
Christian

### More about the problem
Here is the deployment yaml I used:
[pg_deployment.txt](https://github.com/percona/percona-postgresql-operator/files/14361673/pg_deployment.txt)
and here you'll find the errors:
[rancher_error.txt](https://github.com/percona/percona-postgresql-operator/files/14361655/rancher_error.txt)

### Steps to reproduce

1. Installation of the latest Percona PostgreSQL operator (version 2.3.1) in a Rancher cluster
2. Start deployment with the example config and resources specified
3. Checking the created statefullsets and recognizing that the specified resources were not applied correctly

### Versions

1. Kubernetes RKE1
2. Operator 2.3.1
3. Database PostgreSQL 16
4. Rancher 2.7.6

**Comment by spron-in** [comment]
Hey @ChristianHeich-bosch - yeah, we know about this one. Will be fixed under https://perconadev.atlassian.net/browse/K8SPG-513.

If you want to send a PR - always welcome :)
